version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: air -c .air.toml
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/ryoshindo/trivy-api/backend
